In [1]:
class moduleType:

	def __init__(self):
		self.course = None
		self.title = None
		self.au = None
		self.course_type =  None
		self.status = None
		self.su_grade = None
		self.index_number = None
		self.class_type = None
		self.day = None
		self.time = None
		self.venue = None
		self.remark = None

	def __str__(self):
		return 'Course: {} \nTitle: {} \nAU: {} \nCourse Type: {} \nStatus: {} \nS/U: {} \nClass Type: {} \nDay: {} \nTime: {} \nVenue: {} \nRemark: {} \n'.format(\
			self.course, self.title, self.au, self.course_type, self.status, self.su_grade, self.class_type, self.day, self.time, self.venue, self.remark)

In [2]:
import pandas as pd
from icalendar import Calendar, Event

df = pd.read_html(open("try.html"),header=0)
df = df[0]

# remove any exempted module
df = df[df.Status != 'EXEMPTED']
df.reset_index(inplace=True)

In [3]:
df.head()

,index,Course,Title,AU,CourseType,CourseGroup,S/U Grade option,IndexNumber,Status,Choice,ClassType,Group,Day,Time,Venue,Remark
0,0,CC0003,ETHICS & CIVICS IN A MULTICULTURAL WORLD,2.0,CORE,INTERDISCIPLINARY COLLABORATIVE CORE,NaN,10571.0,REGISTERED,NaN,TUT,T69,FRI,1230-1420,LHN-TR+36,"Teaching Wk2,4,6,8,10,12"
1,1,CC0005,HEALTHY LIVING & WELLBEING,3.0,CORE,INTERDISCIPLINARY COLLABORATIVE CORE,NaN,10601.0,REGISTERED,NaN,TUT,T17,TUE,1030-1220,LHN-TR+10,Teaching Wk3-13
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TUT,T17,TUE,1030-1220,ONLINE,"Teaching Wk1,2"
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LEC/STUDIO,LE2,FRI,1630-1720,ONLINE,Teaching Wk1-13
4,5,MH1812,DISCRETE MATHEMATICS,3.0,CORE,NaN,NaN,10137.0,REGISTERED,NaN,TUT,SC13,WED,1330-1420,TR+37,Teaching Wk2-13

In [4]:
import datetime

In [41]:
#---- Obtain class type
def getClassType(classTypeString):
    return classTypeString

#---- Obtain group
def getGroup(groupString):
    return groupString

#---- day
def getDay(dayString):
    # Convert date into integer
    dayDict = {'MON' : 0, 'TUE' : 1, 'WED' : 2, 'THU' : 3, 'FRI' : 4, 'SAT' : 5}
    return dayDict[dayString]

#---- time
def getDuration(timeString):
    timestamp1 = datetime.datetime.strptime(timeString.split('-')[0],"%H%M")
    timestamp2 = datetime.datetime.strptime(timeString.split('-')[1],"%H%M")
    return (timestamp2 - timestamp1).total_seconds()

#---- venue
def getVenue(venueString):
    return venueString

In [39]:
def getStartDate(firstDayOfSchool = datetime.date(2021,8,9)): # get based on fixed value first
    return firstDayOfSchool - datetime.timedelta(days=firstDayOfSchool.weekday())

def getModuleStartWeek(remark, day, startDate):
    # find starting week
    return int(remark[remark.find('Wk')+2])

def getRecurrences(remark):
    remark = remark[remark.find('Wk')+2:]
    # find if there are any commas
    if ',' in remark: # bi-weekly schedule
        return len(remark.split(','))
    else:
        a,b = remark.split('-')
        return b-a+1
def isBiWeekly(remark):
    remark = remark[remark.find('Wk')+2:]
    # find if there are any commas
    if ',' in remark: # bi-weekly schedule
        return True
    return False

In [54]:
import datetime
import pytz
import numpy as np

cal = Calendar()

#---- Find out what is the first day of school
#---- Find out how many teaching weeks are there
#---- Find out when is recess week

startDate = datetime.date.today()

#---- Iterate through the rows ----
for i in range(len(df.index)):
    #---- If row is not Nan, move to next module
    if pd.isnull(df.iloc[i]['Course'])or i==0:
        #---- Obtain class type
        title = getClassType(df.iloc[i]['Title'])
        course = df.iloc[i]['Course']
    #---- If row is Nan, still on the same module ----
    #---- Obtain group
    group = df.iloc[i]['Group']
    indexNumber = df.iloc[i]['IndexNumber']
    classType = getClassType(df.iloc[i]['ClassType'])

    #---- day, implement on start week
    dayInt = getDay(df.iloc[i]['Day'])
    startDay = getModuleStartWeek(df.iloc[i]['Remark'], dayInt, startDate)
    
    #---- time, implement bi or weekly
    time = getDuration(df.iloc[i]['Time']) # time in seconds
    biWeekly = isBiWeekly(df.iloc[i]['Remark'])
    #---- venue
    venue = df.iloc[i]['Venue']
    # obtain the end date
    endDate = startDate
    # ---- Add to event
    event = Event()
    event.add('summary', "{} {} {}".format(course, classType, title))
    event.add('description', indexNumber)
    event.add('dtstart', startDate)
    event.add('duration', datetime.timedelta(seconds=time))
    event.add('dtstamp', datetime.datetime.today())
    event.add('location', venue)
    event.add('rrule', {'freq' : 'weekly', 'until' : endDate})
    cal.add_component(event)
    if i == 5:
        break

f = open('{}.ics'.format('Test'), 'wb')
f.write(cal.to_ical())
f.close()